# Site settings
title: "TestCafe: Web Testing Framework"
baseurl: "/testcafe" 
# url: "http://devexpress.github.io" 
description: >
  TestCafe is the easiest way to automate QA processes and test your websites and apps
  across browsers, operating systems and devices.

copyrightNote: >
  Copyright © 1998-2015 Developer Express Inc.
  
# Build settings
markdown: redcarpet
highlighter: null
redcarpet:
  extensions: ["tables"]