# Site settings
title: "TestCafe: Web Testing Framework"
baseurl: "/test-repo"
# baseurl: "/testcafe" 
# url: "http://devexpress.github.io" 
description: >
  TestCafe is the easiest way to automate QA processes and test your websites and apps
  across browsers, operating systems and devices.

# Build settings
markdown: redcarpet
highlighter: null